services:
  - type: web
    name: ecommerce-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
      - key: JWT_SECRET
